### ISSUE TITLE
enhancement: parsing scalar functions in non-sql statements

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kuneiform#36]
As discussed, we need to support SQL scalar functions.  The hard requirement is to include it in an extension argument, as so:

```typescript
use extension ... as my_extension;

action my_action($string_val) public {
      $my_value = my_extension.my_method(upper($string_val), public_key(@caller));
}
```

It should simply allow the user to use any scalar value supported by Kwil (https://docs.kwil.com/docs/scalar-functions).

As far as I know, this technically uses the action parser (within the engine), and not Kuneiform, but it seems Kuneiform also parses some extensions.  @Yaiba to confirm on this.

I'm open to discussing how this should be handled on the engine side; I think the easiest way is to not modify the current structure for extension calls, and to simply include the function call in the string.  I can handle the downstream effects from there to evaluate:

```golang
type ExtensionCallStmt struct {
	Extension string
	Method    string
	Args      []string
	Receivers []string
}

/*
var extensionCall = &ExtensionCallStmt{
      ...
      Args = []string{'address(@caller)', '$value', '5'}
}
*/
```

I'm flexible on this / open to feedback.

**Comment by Yaiba** [comment]
The action parser is temporary, and only parse what's inside `action`, #7. 

You can think of we put `action` syntax check in Kuneiform, and put actual parsing in:
- actparser, for non-sql statements
- sqlparser, for sql statements

So to support this, I'll need to change both ANTLR syntax in Kuneiform and actparser, add parsing logic to actparser.

It would be consistent and also suitable(since Kuneiform has no plan to do any evaluation, for now) to let engine handle `scalar` functions

**Comment by Yaiba** [comment]
We choose to change `ExtensionCallStmt.Args` and `ActionCallStmt.Args` types to `sqlparser.Expression`, to unlease more features on extension call and action call
